DROP TABLE IF EXISTS wb.order_item CASCADE;
DROP TABLE IF EXISTS wb.order CASCADE;
DROP TABLE IF EXISTS wb.item CASCADE;
DROP TABLE IF EXISTS wb.payment CASCADE;
DROP TABLE IF EXISTS wb.delivery CASCADE;
DROP SCHEMA wb;